## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("../Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Kieta,PG,84.04,light rain,-6.2167,155.6333,Uruna Bay Retreat
1,2,Avarua,CK,82.45,few clouds,-21.2078,-159.7750,Paradise Inn
2,3,Hirara,JP,75.47,broken clouds,24.8000,125.2833,Hotel Atoll Emerald Miyakojima
3,4,Cabo San Lucas,MX,88.61,overcast clouds,22.8909,-109.9124,Hotel Tesoro Los Cabos
4,12,Morant Bay,JM,80.22,overcast clouds,17.8815,-76.4093,Whispering Bamboo Cove Resort

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [15]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
cities_vacation_df = vacation_df.loc[(vacation_df["Country"] == "AU" )]
cities_vacation_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
8,29,Port Hedland,AU,87.85,clear sky,-20.3167,118.5667,The Esplanade Hotel
39,134,Dalby,AU,81.99,clear sky,-27.1833,151.2667,Kobbers Motor Inn Dalby
68,297,Bundaberg,AU,85.21,scattered clouds,-24.8500,152.3500,Takalvan Motel
75,324,Bowen,AU,86.22,few clouds,-20.0167,148.2333,Castle Motor Lodge Motel
80,347,Yulara,AU,84.04,few clouds,-25.2406,130.9889,Desert Gardens Hotel - Ayers Rock Resort
84,357,Emerald,AU,84.34,broken clouds,-23.5333,148.1667,The Irish Village
102,427,Alice Springs,AU,76.55,clear sky,-23.7000,133.8833,Desert Palms Alice Springs
124,509,Charters Towers,AU,88.09,few clouds,-20.1000,146.2667,Cattleman's Rest Motor Inn
137,550,Mount Isa,AU,85.77,clear sky,-20.7333,139.5000,ibis Styles Mt Isa Verona
139,555,Ballina,AU,75.38,broken clouds,-28.8667,153.5667,Ramada Hotel & Suites by Wyndham Ballina Byron
143,584,Gold Coast,AU,78.39,scattered clouds,-28.0000,153.4333,Mantra Towers of Chevron Surfers Paradise
144,585,Blackwater,AU,85.32,clear sky,-23.5833,148.8833,Blackwater Motor Inn
172,665,Byron Bay,AU,75.31,broken clouds,-28.6500,153.6167,Backpackers Inn on the Beach
173,667,Mackay,AU,88.68,clear sky,-21.1500,149.2000,International Lodge Motel

In [44]:
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.
vacation_start = vacation_df.loc[(vacation_df["City"] == "Charters Towers")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Charters Towers")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Mount Isa")]
vacation_stop2 = cities_vacation_df.loc[(cities_vacation_df["City"] == "Alice Springs")]
vacation_stop3 = cities_vacation_df.loc[(cities_vacation_df["City"] == "Yulara")]
vacation_start

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
124,509,Charters Towers,AU,88.09,few clouds,-20.1,146.2667,Cattleman's Rest Motor Inn

In [80]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start["Lat"].to_numpy()[0], vacation_start["Lng"].to_numpy()[0]
end = vacation_end["Lat"].to_numpy()[0], vacation_end["Lng"].to_numpy()[0]
stop1 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop1["Lng"].to_numpy()[0]
stop2 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop2["Lng"].to_numpy()[0]
stop3 = vacation_stop1["Lat"].to_numpy()[0], vacation_stop3["Lng"].to_numpy()[0]
print(f"Start: {start}, End: {end}, stop1: {stop1}, stop2: {stop2}, stop3: {stop3}")

Start: (-20.1, 146.2667), End: (-20.1, 146.2667), stop1: (-20.7333, 139.5), stop2: (-20.7333, 133.8833), stop3: (-20.7333, 130.9889)

In [81]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
itinerary_df = gmaps.directions_layer(
    start, end, waypoints=[stop1, stop2, stop3], 
    travel_mode="DRIVING")

fig.add_layer(itinerary_df)
fig

Figure(layout=FigureLayout(height='420px'))

In [69]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,509,Charters Towers,AU,88.09,few clouds,-20.1000,146.2667,Cattleman's Rest Motor Inn
1,550,Mount Isa,AU,85.77,clear sky,-20.7333,139.5000,ibis Styles Mt Isa Verona
2,427,Alice Springs,AU,76.55,clear sky,-23.7000,133.8833,Desert Palms Alice Springs
3,347,Yulara,AU,84.04,few clouds,-25.2406,130.9889,Desert Gardens Hotel - Ayers Rock Resort

In [70]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City Name</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} Â°F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [71]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))